version: "2"
networks:
  app-tier:
    driver: bridge
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      --bind_ip_all
    networks:
      - app-tier
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
