version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scheduling
    ports:
      - "3306:3306"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge